version: "3.8"

services:
  cms:
    build: .
    container_name: cms-mock-service
    ports:
      - "5001:5001"
    environment:
      - SERVER_PORT=5001
      - SPRING_APPLICATION_NAME=cms-mock
      - JAVA_OPTS=-Xmx512m -Xms256m
